default: &default
  adapter: mysql2
  host: localhost
  username: root
  password: garbana
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ESB_dev

test:
  <<: *default
  database: ESB_test

production:
  <<: *default
  database: ESB_prod
